name: Apply Terraform Templates
on:
  workflow_dispatch:
    inputs:
      domain_name:
        description: "The domain name of the web app (e.g. example.com, requires setup of ACM cert for this domain and www. subdomain as well as Hosted Zone)"
        required: false
        default: ""
      stack:
        description: "Select a stack"
        type: choice
        options:
          - "s3"
          - "ecs"
        default: "s3"
jobs:
  apply-terraform:
    permissions:
      id-token: write
      contents: read
    uses: izzy456/colour-in-workflows/.github/workflows/apply-terraform.yml@main
    with:
      branch: ${{ github.ref_name }}
      project-name: ${{ inputs.stack }}
      aws-region: ${{ vars.AWS_REGION }}
      copy-args: "-r ../common/."
      tf-vars: ${{ inputs.stack=='s3' && format('region={0} domain_name={1}', vars.AWS_REGION, vars.DOMAIN_NAME) || format('region={0}', vars.AWS_REGION) }}
    secrets:
      aws-role: ${{ secrets.AWS_ROLE }}
