name: Check Terraform Templates - ECS
on:
  push:
    branches:
      - develop
      - "feature/**"
      - "hotfix/**"
    paths:
      - "ecs/**"
  workflow_dispatch:
jobs:
  check-terraform:
    permissions:
      id-token: write
      contents: read
    uses: izzy456/colour-in-workflows/.github/workflows/check-terraform.yml@main
    with:
      branch: ${{ github.ref_name }}
      project-name: ecs
      aws-region: ${{ vars.AWS_REGION }}
      copy-args: "-r ../common/."
      tf-vars: "region=${{ vars.AWS_REGION }}"
    secrets:
      aws-role: ${{ secrets.AWS_ROLE }}
      sonar-token: ${{ secrets.SONAR_TOKEN_ECS }}
      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
