name: Check Terraform Templates - S3
on:
  push:
    branches:
      - develop
      - "feature/**"
      - "hotfix/**"
    paths:
      - "s3/**"
  workflow_dispatch:
jobs:
  check-terraform:
    permissions:
      id-token: write
      contents: read
    uses: izzy456/colour-in-workflows/.github/workflows/check-terraform.yml@main
    with:
      branch: ${{ github.ref_name }}
      project-name: s3
      aws-region: ${{ vars.AWS_REGION }}
      copy-args: "-r ../common/."
      tf-vars: "domain_name=${{ vars.DOMAIN_NAME }} region=${{ vars.AWS_REGION }}"
    secrets:
      aws-role: ${{ secrets.AWS_ROLE }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
