name: Drift Check - S3
on:
  # schedule:
  #   - cron: "0 8 * * 1-5"
  workflow_dispatch:
jobs:
  terraform-drift-check:
    permissions:
      id-token: write
      contents: read
    uses: izzy456/colour-in-workflows/.github/workflows/terraform-drift-check.yml@main
    with:
      branch: "main"
      project-name: s3
      aws-region: ${{ vars.AWS_REGION }}
      copy-args: "-r ../common/."
      tf-vars: domain_name=${{ vars.DOMAIN_NAME }} region=${{ vars.AWS_REGION }}
    secrets:
      aws-role: ${{ secrets.AWS_ROLE }}
